# Generated by Django 2.0.2 on 2018-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareimg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedimage',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
