# Generated by Django 2.0.2 on 2018-04-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='created',
        ),
    ]
